services:
    ImportDefinitionsBundle\Command\ListImportDefinitionsCommand:
        tags:
            - { name: 'console.command', command: 'import-definitions:list' }

    ImportDefinitionsBundle\Command\ListExportDefinitionsCommand:
        tags:
            - { name: 'console.command', command: 'export-definitions:list' }

    ImportDefinitionsBundle\Command\ImportCommand:
        arguments:
            - '@event_dispatcher'
            - '@import_definitions.repository.definition'
            - '@import_definition.importer'
        tags:
            - { name: 'console.command', command: 'import-definitions:import' }

    ImportDefinitionsBundle\Command\ExportCommand:
        arguments:
            - '@event_dispatcher'
            - '@import_definitions.repository.export_definition'
            - '@import_definition.exporter'
        tags:
            - { name: 'console.command', command: 'export-definitions:export' }

    ImportDefinitionsBundle\Command\ImportImportDefinitionCommand:
        arguments:
            - "@=service('coreshop.resource_registry').get('import_definitions.definition')"
            - '@import_definitions.repository.definition'
            - '@pimcore.dao.object_manager'
            - '@coreshop.resource_controller.form_factory'
        tags:
            - { name: 'console.command', command: 'import-definitions:definition:import' }

    ImportDefinitionsBundle\Command\ImportExportDefinitionCommand:
        arguments:
            - "@=service('coreshop.resource_registry').get('import_definitions.export_definition')"
            - '@import_definitions.repository.export_definition'
            - '@pimcore.dao.object_manager'
            - '@coreshop.resource_controller.form_factory'
        tags:
            - { name: 'console.command', command: 'export-definitions:definition:import' }
